routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Auth::routes(['verify' => true]);

// Admin Routes
Route::get('admin', function(){
    return redirect()->route('admin.signin');
});

Route::get('/', ['as' => 'admin.signin', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::get('/verify/registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\VerificationController@verifyUser']);
Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('set_password', ['as' => 'password.set', 'uses' => 'Auth\SetPasswordController@set_password']);


Route::post('item-details', ['as' => 'search.item_details', 'uses' => 'SearchController@item_details']);
Route::post('sale-item-details', ['as' => 'search.sale_item_details', 'uses' => 'SearchController@sale_item_details']);
Route::post('sale-bags', ['as' => 'search.sale_bags', 'uses' => 'SearchController@sale_bags']);
Route::post('supplier-info', ['as' => 'search.supplier_info', 'uses' => 'SearchController@supplier_info']);
Route::post('customer-info', ['as' => 'search.customer_info', 'uses' => 'SearchController@customer_info']);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::group([
        'middleware' => ['auth', 'role:developer|admin|super-admin'],
    ], function () {

        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::resource('memberships','MembershipController');
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');

        Route::resource('payment_methods','PaymentMethodController');

        Route::resource('members','MemberController');
        Route::resource('users','UserController');
        Route::resource('units','UnitController');

    });
});


Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'as' => 'member.'
], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::group([
        'middleware' => ['auth', 'role:master-member|developer|admin|super-admin'],
    ], function () {

        Route::resource('settings','SettingController');
        Route::resource('users','UserController');
        Route::get('set-users-company', ['as' => 'users.set_users_company', 'uses' => 'UserController@set_users_company']);
        Route::post('set-users-company', ['as' => 'users.save_users_company', 'uses' => 'UserController@save_users_company']);
        Route::get('set-users-branch', ['as' => 'users.set_users_branch', 'uses' => 'UserController@set_users_branch']);
        Route::post('set-users-branch', ['as' => 'users.save_users_branch', 'uses' => 'UserController@save_users_branch']);
        Route::get('general-settings', ['as' => 'settings.general_settings', 'uses' => 'SettingController@general_settings']);
        Route::post('set-print-page-setup', ['as' => 'settings.set_print_page_setup', 'uses' => 'SettingController@set_print_page_setup']);

        Route::resource('branch','BranchController');
        Route::resource('categories','CategoryController');

    });
//
//    Route::group([
//        'middleware' => ['auth', 'role:user|accountant|master-member|developer|admin|super-admin'],
//    ], function () {


        Route::resource('items','ItemController');

        Route::get('print-barcode-form', ['as' => 'items.print_barcode_form', 'uses' => 'ItemController@print_barcode_form']);
        Route::get('print-barcode', ['as' => 'items.print_barcode', 'uses' => 'ItemController@print_barcode']);

        Route::resource('cash_or_bank_accounts','CashBankAccountController');
        Route::resource('company','CompanyController');

        Route::resource('sharer','SharerController');
        Route::get('sharer/create/{type}', ['as' => 'sharer.create', 'uses' => 'SharerController@create']);
        Route::get('customer-list', ['as' => 'sharer.customer_list', 'uses' => 'SharerController@customer_list']);
        Route::get('supplier-list', ['as' => 'sharer.supplier_list', 'uses' => 'SharerController@supplier_list']);

        Route::post('account-type-save', ['as' => 'account_type.save', 'uses' => 'CommonController@saveAccountType']);
        Route::post('customer-save', ['as' => 'customer.save', 'uses' => 'CommonController@saveCustomer']);
        Route::post('payer-search', ['as' => 'payer.search', 'uses' => 'CommonController@payerSearch']);

        Route::get('report/list', ['as' => 'report.list', 'uses' => 'ReportController@report_list']);
        Route::get('report/daily-stocks', ['as' => 'report.daily_stocks', 'uses' => 'ReportController@daily_stocks']);
        Route::get('report/stocks', ['as' => 'report.stocks', 'uses' => 'ReportController@stocks']);
        Route::get('report/total_stocks', ['as' => 'report.total_stocks', 'uses' => 'ReportController@total_stocks']);
        Route::get('report/cost/{type}', ['as' => 'report.cost', 'uses' => 'ReportController@cost_report']);
        Route::get('report/daily-sheet', ['as' => 'report.daily_sheet', 'uses' => 'ReportController@daily_sheet']);
        Route::get('report/sharer-due/{type}', ['as' => 'report.sharer_due', 'uses' => 'ReportController@sharer_due_report']);
        Route::get('report/sharer-due-collection/{type}', ['as' => 'report.sharer_due_collection', 'uses' => 'ReportController@sharer_due_collection_report']);
        Route::get('report/inventory-due/{type}', ['as' => 'report.inventory_due', 'uses' => 'ReportController@inventory_due_report']);
        Route::get('report/inventory/{type}', ['as' => 'report.inventory', 'uses' => 'ReportController@inventory_report']);
        Route::get('report/balance-sheet', ['as' => 'report.balance_sheet', 'uses' => 'ReportController@balance_sheet']);
        Route::get('report/product-purchase', ['as' => 'report.product_purchase_report', 'uses' => 'ReportController@product_purchase_report']);
        Route::get('report/supplier-purchase', ['as' => 'report.supplier_purchase', 'uses' => 'ReportController@supplier_purchase_report']);
        Route::get('report/sale', ['as' => 'report.sale', 'uses' => 'ReportController@sale_report']);
        Route::get('report/purchase', ['as' => 'report.purchase', 'uses' => 'ReportController@purchase_report']);

        Route::resource('purchase','PurchaseController');
        Route::get('purchase-due-list', [ 'as'=>'purchase.due_list','uses'=>'PurchaseController@due_list']);
        Route::get('purchase-due-payment/{id}', [ 'as'=>'purchase.due_payment','uses'=>'PurchaseController@due_payment']);
        Route::post('purchase-due-receive/{id}', [ 'as'=>'purchase.receive_due_payment','uses'=>'PurchaseController@receive_due_payment']);
        Route::resource('purchase_return','PurchaseReturnController');
        Route::get('purchase_return/view_returns/{id}/{code}', [ 'as'=>'purchase_return.view_returns','uses'=>'PurchaseReturnController@view_returns']);


        Route::resource('sales','SalesController');
        Route::get('sales-due-list', [ 'as'=>'sales.due_list','uses'=>'SalesController@due_list']);
        Route::get('sales-return-list', [ 'as'=>'sales.sales_return_list','uses'=>'SalesController@sales_return_list']);
        Route::get('sales-return/{id}', [ 'as'=>'sales.sales_return','uses'=>'SalesController@sales_return']);
        Route::put('sales-return-update/{id}', [ 'as'=>'sales.sales_return_update','uses'=>'SalesController@sales_return_update']);
        Route::get('sales/view_return/{id}/{code}', [ 'as'=>'sales.view_return','uses'=>'SalesController@sale_return_view']);
        Route::get('sales-due-payment/{id}', [ 'as'=>'sales.due_payment','uses'=>'SalesController@due_payment']);
        Route::post('sales-due-receive/{id}', [ 'as'=>'sales.receive_due_payment','uses'=>'SalesController@receive_due_payment']);
        Route::get('print-sale/{id}', [ 'as'=>'sales.print_sale','uses'=>'SalesController@print_sale']);

//    });

});

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\MembersDataTable;
use App\Models\Country;
use App\Models\Member;
use App\Models\Membership;
use App\Models\Role;
use App\Models\User;
use App\Notifications\VerifyUser;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Http\Traits\VerifyUserTrait;

class MemberController extends Controller
{
    use VerifyUserTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(MembersDataTable $dataTable)
    {
        return $dataTable->render('admin.members.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $packages = Membership::where('status', 'active')->get();
        $data['memberships'] = $packages->pluck('packages', 'id');
        $data['countries'] = Country::pluck('countryName', 'id');


        return view('admin.members.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->getValidationRules());

        $member = array();
        $member['member_code'] = member_code_generate();
        $member['api_access_key'] = api_access_key_generate($request->full_name);
        $member['membership_id'] = $request->membership_id;
        $packages = Membership::find($request->membership_id);

        if($packages->time_period == 0)
        {
            $member['expire_date'] = Carbon::maxValue();
        }else{
            $member['expire_date'] = Carbon::now()->addMonths($packages->time_period);
        }
        $member['country_id'] = $request->country_id;
        $member['status'] = $request->status;

        DB::beginTransaction();

        try{
            $saveMember = Member::create($member);
//            $saveMember->save();


            // Set Member As a User
            $user = array();
            $user['full_name'] = $request->full_name;
            $user['email'] = $email = $request->email;
            $user['phone'] = $request->phone;
            $user['membership_id'] = $request->membership_id;
            $user['verify_token'] = $verify_token = verify_token_generate();
            $user['status'] = $request->status;
            $saveUser = $saveMember->users()->create($user);
//            $saveUser->save();

            // Find Master Member Role
            $memberRole = Role::where('name', 'master-member')->first();
            $assignRole = $saveUser->roles()->attach($memberRole->id);

            $this->sendVerifyToken($verify_token, $email);

        }catch (\Exception $e){

            DB::rollBack();
        }

        DB::commit();

        $status = ['type' => 'success', 'message' => 'Member Added Successfully'];

        return back()->with('status', $status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['member'] = $member = Member::findOrFail($id);
        $data['user'] = $member->users()->first();
        $packages = Membership::where('status', 'active')->get();
        $data['memberships'] = $packages->pluck('packages', 'id');
        $data['countries'] = Country::pluck('countryName', 'id');

        return view('admin.members.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $findMember = Member::findOrFail($id);
        $masterUser = User::where('member_id', $id)->first();
        $user_id = $findMember->users()->first()->id;

        $this->validate($request, $this->getValidationRules($user_id));

        $member = array();
        $member['membership_id'] = $request->membership_id;
        $packages = Membership::find($request->membership_id);

        if($packages->time_period == 0)
        {
            $member['expire_date'] = Carbon::maxValue();
        }else{
            $member['expire_date'] = Carbon::now()->addMonths($packages->time_period);
        }
        $member['country_id'] = $request->country_id;
        $member['status'] = $request->status;

        DB::beginTransaction();

        try{
            $saveMember = $findMember->update($member);

//            print_r($request->full_name); exit;
            // Set Member As a User
            $masterUser->full_name = $request->full_name;
            $masterUser->email = $request->email;
            $masterUser->phone = $request->phone;
            $masterUser->membership_id = $request->membership_id;
            $masterUser->status = $request->status;
            $masterUser->save();

        }catch (\Exception $e){

            DB::rollBack();
        }

        DB::commit();

        $status = ['type' => 'success', 'message' => 'Member Updated Successfully'];

        return back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function getValidationRules($id='')
    {
        $rules = [
            'full_name' => 'required',
            'membership_id' => 'required',
        ];

        if (is_null($id)) {
            $rules['email'] = 'required|email|unique:users';
            $rules['phone'] = 'nullable|unique:users,phone';
        } else {
            $rules['email'] = 'required|email|unique:users,email,' . $id;
            $rules['phone'] = 'nullable|unique:users,phone,' . $id;
        }

        return $rules;
    }
}

app/Http/Controllers/Member/BranchController.php
<?php

namespace App\Http\Controllers\Member;

use App\DataTables\BranchDataTable;
use App\Models\Branch;
use App\Models\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(BranchDataTable $dataTable)
    {
        return $dataTable->render('member.branches.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['countries'] = Country::all()->pluck('countryName', 'id');

        return view('member.branches.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, $this->validationRules());

        $inputs = $request->all();
        $inputs['name'] = human_words($inputs['display_name']);
        Branch::create($inputs);


        $status = ['type' => 'success', 'message' => 'Successfully Added.'];

        return back()->with('status', $status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['model'] = Branch::findOrFail($id);
        $data['countries'] = Country::all()->pluck('countryName', 'id');

        return view('member.branches.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Branch::findOrFail($id);
        $this->validate($request, $this->validationRules());

        $inputs = $request->all();
        $inputs['name'] = human_words($inputs['display_name']);
        $company->update($inputs);

        $status = ['type' => 'success', 'message' => 'Successfully Updated'];

        return back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function validationRules(){

        $rules = [
            'display_name' => 'required',
            'phone' => 'required',
        ];

        return $rules;
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
     public function index(){
        return view('member.dashboard.index');
    }
}

resources/views/member/branches/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 4:25 PM
 */

?>

@push('styles')
    <link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/select2/dist/css/select2.min.css')}}">
@endpush


<div class="col-md-6">
    <div class="form-group">
        <label for="name">Branch Name<span class="text-red"> * </span> </label>
        {!! Form::text('display_name',null,['id'=>'display_name','class'=>'form-control','placeholder'=>'Enter Branch Name', 'required']); !!}
    </div>
    <div class="form-group">
        <label for="phone">Phone No<span class="text-red"> * </span> </label>
        {!! Form::text('phone',null,['id'=>'phone','class'=>'form-control','placeholder'=>'Enter Phone No', 'required']); !!}
    </div>
    <div class="form-group">
        <label for="phone">Email<span class="text-red"> * </span> </label>
        {!! Form::text('email',null,['id'=>'email','class'=>'form-control ','placeholder'=>'Enter Email', 'required']); !!}
    </div>


    <div class="form-group">
        <label for="display_name">Address <span class="text-red"> * </span> </label>
        {!! Form::textarea('address',null,['id'=>'address','class'=>'form-control','placeholder'=>'Enter Address',  'rows'=>"2"]); !!}
    </div>
    <div class="form-group">
        <label for="city">City  </label>
        {!! Form::text('city',null,['id'=>'city','class'=>'form-control','placeholder'=>'Enter City']); !!}
    </div>
    <div class="form-group">
        <label for="display_name">Country <span class="text-red"> * </span> </label>
        {!! Form::select('country_id',$countries,null,['id'=>'country','class'=>'form-control select2','placeholder'=>'Select Country','required']); !!}
    </div>
</div>

    @push('scripts')
    <!-- Select2 -->
    <script src="{{ asset('public/adminLTE/bower_components/select2/dist/js/select2.full.min.js') }}"></script>

    <script type="text/javascript">

          $(function () {

            $('.select2').select2()
        });

    </script>


@endpush

resources/views/member/branches/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 12:52 PM
 */
 

$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Branch',
        'href' => route('member.branch.index'),
    ],
    [
        'name' => 'Create',
    ],
];

$data['data'] = [
    'name' => 'Branch',
    'title'=>'Create Branch',
    'heading' => 'Create Branch',
];

?>

 

@extends('layouts.back-end.master', $data)

@section('contents')
<div class="row">
    <!-- left column -->
    <div class="col-md-12">

        @include('common._alert')

        @include('common._error')
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create Branch</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->

            {!! Form::open(['route' => 'member.branch.store','method' => 'POST','files'=>'true','role'=>'form' ]) !!}

            <div class="box-body">

                @include('member.branches._form')

                <div class="box-footer">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            </div>
            <!-- /.box-body -->

            {!! Form::close() !!}
            <!-- /.box -->
        </div>
    </div>
</div>
@endsection

resources/views/member/branches/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 12:52 PM
 */
$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Branch',
        'href' => route('member.branch.index'),
    ],
    [
        'name' => 'Edit',
    ],
];

$data['data'] = [
    'name' => 'Branch',
    'title'=>'Edit Branch',
    'heading' => 'Edit Branch',
];

?>



@extends('layouts.back-end.master', $data)

@section('contents')
<div class="row">
    <!-- left column -->
    <div class="col-md-12">

        @include('common._alert')

        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Update </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->

            {!! Form::model($model, ['route' => ['member.branch.update', $model],  'method' => 'put']) !!}

            <div class="box-body">

                @include('member.branches._form')

                <div class="box-footer">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>

            </div>
            <!-- /.box-body -->

            {!! Form::close() !!}
            <!-- /.box -->
        </div>
    </div>
</div>
@endsection


@push('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('public/vendor/datatables/buttons.server-side.js') }}"></script>

@endpush

resources/views/member/branches/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Branch',
        'href' => route('member.branch.index'),
    ],
    [
        'name' => 'Index',
    ],
];

$data['data'] = [
    'name' => 'Branches',
    'title'=>'List Of Branches',
    'heading' => 'List Of Branches',
];

?>

@extends('layouts.back-end.master', $data)

@section('contents')


    <div class="row">
        <div class="col-xs-12">

            @include('common._alert')

            <div class="box">
                <div class="portlet light">

                    <div class="box-header">
                        <a href="{{ route('member.branch.create') }}" class="btn btn-info"> <i class="fa fa-plus"> Add Branches </i></a>
                    </div>
                    <!-- END SAMPLE FORM PORTLET-->
                </div>
                <div class="box-body">
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <!-- BEGIN SAMPLE FORM PORTLET-->

                        <div class="table-responsive">
                            {!! $dataTable->table() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('public/vendor/datatables/buttons.server-side.js') }}"></script>
    {!! $dataTable->scripts() !!}
@endpush