routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Auth::routes(['verify' => true]);

// Admin Routes
Route::get('admin', function(){
    return redirect()->route('admin.signin');
});

Route::get('/', ['as' => 'admin.signin', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::get('/verify/registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\VerificationController@verifyUser']);
Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('set_password', ['as' => 'password.set', 'uses' => 'Auth\SetPasswordController@set_password']);


Route::post('item-details', ['as' => 'search.item_details', 'uses' => 'SearchController@item_details']);
Route::post('sale-item-details', ['as' => 'search.sale_item_details', 'uses' => 'SearchController@sale_item_details']);
Route::post('sale-bags', ['as' => 'search.sale_bags', 'uses' => 'SearchController@sale_bags']);
Route::post('supplier-info', ['as' => 'search.supplier_info', 'uses' => 'SearchController@supplier_info']);
Route::post('customer-info', ['as' => 'search.customer_info', 'uses' => 'SearchController@customer_info']);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::group([
        'middleware' => ['auth', 'role:developer|admin|super-admin'],
    ], function () {

        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::resource('memberships','MembershipController');
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');

        Route::resource('payment_methods','PaymentMethodController');

        Route::resource('members','MemberController');
        Route::resource('users','UserController');
        Route::resource('units','UnitController');

    });
});


Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'as' => 'member.'
], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::group([
        'middleware' => ['auth', 'role:master-member|developer|admin|super-admin'],
    ], function () {

        Route::resource('settings','SettingController');
        Route::resource('users','UserController');
        Route::get('set-users-company', ['as' => 'users.set_users_company', 'uses' => 'UserController@set_users_company']);
        Route::post('set-users-company', ['as' => 'users.save_users_company', 'uses' => 'UserController@save_users_company']);
        Route::get('set-users-branch', ['as' => 'users.set_users_branch', 'uses' => 'UserController@set_users_branch']);
        Route::post('set-users-branch', ['as' => 'users.save_users_branch', 'uses' => 'UserController@save_users_branch']);
        Route::get('general-settings', ['as' => 'settings.general_settings', 'uses' => 'SettingController@general_settings']);
        Route::post('set-print-page-setup', ['as' => 'settings.set_print_page_setup', 'uses' => 'SettingController@set_print_page_setup']);

        Route::resource('branch','BranchController');
        Route::resource('categories','CategoryController');

    });
//
//    Route::group([
//        'middleware' => ['auth', 'role:user|accountant|master-member|developer|admin|super-admin'],
//    ], function () {


        Route::resource('items','ItemController');

        Route::get('print-barcode-form', ['as' => 'items.print_barcode_form', 'uses' => 'ItemController@print_barcode_form']);
        Route::get('print-barcode', ['as' => 'items.print_barcode', 'uses' => 'ItemController@print_barcode']);

        Route::resource('cash_or_bank_accounts','CashBankAccountController');
        Route::resource('company','CompanyController');

        Route::resource('sharer','SharerController');
        Route::get('sharer/create/{type}', ['as' => 'sharer.create', 'uses' => 'SharerController@create']);
        Route::get('customer-list', ['as' => 'sharer.customer_list', 'uses' => 'SharerController@customer_list']);
        Route::get('supplier-list', ['as' => 'sharer.supplier_list', 'uses' => 'SharerController@supplier_list']);

        Route::post('account-type-save', ['as' => 'account_type.save', 'uses' => 'CommonController@saveAccountType']);
        Route::post('customer-save', ['as' => 'customer.save', 'uses' => 'CommonController@saveCustomer']);
        Route::post('payer-search', ['as' => 'payer.search', 'uses' => 'CommonController@payerSearch']);

        Route::get('report/list', ['as' => 'report.list', 'uses' => 'ReportController@report_list']);
        Route::get('report/daily-stocks', ['as' => 'report.daily_stocks', 'uses' => 'ReportController@daily_stocks']);
        Route::get('report/stocks', ['as' => 'report.stocks', 'uses' => 'ReportController@stocks']);
        Route::get('report/total_stocks', ['as' => 'report.total_stocks', 'uses' => 'ReportController@total_stocks']);
        Route::get('report/cost/{type}', ['as' => 'report.cost', 'uses' => 'ReportController@cost_report']);
        Route::get('report/daily-sheet', ['as' => 'report.daily_sheet', 'uses' => 'ReportController@daily_sheet']);
        Route::get('report/sharer-due/{type}', ['as' => 'report.sharer_due', 'uses' => 'ReportController@sharer_due_report']);
        Route::get('report/sharer-due-collection/{type}', ['as' => 'report.sharer_due_collection', 'uses' => 'ReportController@sharer_due_collection_report']);
        Route::get('report/inventory-due/{type}', ['as' => 'report.inventory_due', 'uses' => 'ReportController@inventory_due_report']);
        Route::get('report/inventory/{type}', ['as' => 'report.inventory', 'uses' => 'ReportController@inventory_report']);
        Route::get('report/balance-sheet', ['as' => 'report.balance_sheet', 'uses' => 'ReportController@balance_sheet']);
        Route::get('report/product-purchase', ['as' => 'report.product_purchase_report', 'uses' => 'ReportController@product_purchase_report']);
        Route::get('report/supplier-purchase', ['as' => 'report.supplier_purchase', 'uses' => 'ReportController@supplier_purchase_report']);
        Route::get('report/sale', ['as' => 'report.sale', 'uses' => 'ReportController@sale_report']);
        Route::get('report/purchase', ['as' => 'report.purchase', 'uses' => 'ReportController@purchase_report']);

        Route::resource('purchase','PurchaseController');
        Route::get('purchase-due-list', [ 'as'=>'purchase.due_list','uses'=>'PurchaseController@due_list']);
        Route::get('purchase-due-payment/{id}', [ 'as'=>'purchase.due_payment','uses'=>'PurchaseController@due_payment']);
        Route::post('purchase-due-receive/{id}', [ 'as'=>'purchase.receive_due_payment','uses'=>'PurchaseController@receive_due_payment']);
        Route::resource('purchase_return','PurchaseReturnController');
        Route::get('purchase_return/view_returns/{id}/{code}', [ 'as'=>'purchase_return.view_returns','uses'=>'PurchaseReturnController@view_returns']);


        Route::resource('sales','SalesController');
        Route::get('sales-due-list', [ 'as'=>'sales.due_list','uses'=>'SalesController@due_list']);
        Route::get('sales-return-list', [ 'as'=>'sales.sales_return_list','uses'=>'SalesController@sales_return_list']);
        Route::get('sales-return/{id}', [ 'as'=>'sales.sales_return','uses'=>'SalesController@sales_return']);
        Route::put('sales-return-update/{id}', [ 'as'=>'sales.sales_return_update','uses'=>'SalesController@sales_return_update']);
        Route::get('sales/view_return/{id}/{code}', [ 'as'=>'sales.view_return','uses'=>'SalesController@sale_return_view']);
        Route::get('sales-due-payment/{id}', [ 'as'=>'sales.due_payment','uses'=>'SalesController@due_payment']);
        Route::post('sales-due-receive/{id}', [ 'as'=>'sales.receive_due_payment','uses'=>'SalesController@receive_due_payment']);
        Route::get('print-sale/{id}', [ 'as'=>'sales.print_sale','uses'=>'SalesController@print_sale']);

//    });

});

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\MembersDataTable;
use App\Models\Country;
use App\Models\Member;
use App\Models\Membership;
use App\Models\Role;
use App\Models\User;
use App\Notifications\VerifyUser;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Http\Traits\VerifyUserTrait;

class MemberController extends Controller
{
    use VerifyUserTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(MembersDataTable $dataTable)
    {
        return $dataTable->render('admin.members.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $packages = Membership::where('status', 'active')->get();
        $data['memberships'] = $packages->pluck('packages', 'id');
        $data['countries'] = Country::pluck('countryName', 'id');


        return view('admin.members.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->getValidationRules());

        $member = array();
        $member['member_code'] = member_code_generate();
        $member['api_access_key'] = api_access_key_generate($request->full_name);
        $member['membership_id'] = $request->membership_id;
        $packages = Membership::find($request->membership_id);

        if($packages->time_period == 0)
        {
            $member['expire_date'] = Carbon::maxValue();
        }else{
            $member['expire_date'] = Carbon::now()->addMonths($packages->time_period);
        }
        $member['country_id'] = $request->country_id;
        $member['status'] = $request->status;

        DB::beginTransaction();

        try{
            $saveMember = Member::create($member);
//            $saveMember->save();


            // Set Member As a User
            $user = array();
            $user['full_name'] = $request->full_name;
            $user['email'] = $email = $request->email;
            $user['phone'] = $request->phone;
            $user['membership_id'] = $request->membership_id;
            $user['verify_token'] = $verify_token = verify_token_generate();
            $user['status'] = $request->status;
            $saveUser = $saveMember->users()->create($user);
//            $saveUser->save();

            // Find Master Member Role
            $memberRole = Role::where('name', 'master-member')->first();
            $assignRole = $saveUser->roles()->attach($memberRole->id);

            $this->sendVerifyToken($verify_token, $email);

        }catch (\Exception $e){

            DB::rollBack();
        }

        DB::commit();

        $status = ['type' => 'success', 'message' => 'Member Added Successfully'];

        return back()->with('status', $status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['member'] = $member = Member::findOrFail($id);
        $data['user'] = $member->users()->first();
        $packages = Membership::where('status', 'active')->get();
        $data['memberships'] = $packages->pluck('packages', 'id');
        $data['countries'] = Country::pluck('countryName', 'id');

        return view('admin.members.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $findMember = Member::findOrFail($id);
        $masterUser = User::where('member_id', $id)->first();
        $user_id = $findMember->users()->first()->id;

        $this->validate($request, $this->getValidationRules($user_id));

        $member = array();
        $member['membership_id'] = $request->membership_id;
        $packages = Membership::find($request->membership_id);

        if($packages->time_period == 0)
        {
            $member['expire_date'] = Carbon::maxValue();
        }else{
            $member['expire_date'] = Carbon::now()->addMonths($packages->time_period);
        }
        $member['country_id'] = $request->country_id;
        $member['status'] = $request->status;

        DB::beginTransaction();

        try{
            $saveMember = $findMember->update($member);

//            print_r($request->full_name); exit;
            // Set Member As a User
            $masterUser->full_name = $request->full_name;
            $masterUser->email = $request->email;
            $masterUser->phone = $request->phone;
            $masterUser->membership_id = $request->membership_id;
            $masterUser->status = $request->status;
            $masterUser->save();

        }catch (\Exception $e){

            DB::rollBack();
        }

        DB::commit();

        $status = ['type' => 'success', 'message' => 'Member Updated Successfully'];

        return back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function getValidationRules($id='')
    {
        $rules = [
            'full_name' => 'required',
            'membership_id' => 'required',
        ];

        if (is_null($id)) {
            $rules['email'] = 'required|email|unique:users';
            $rules['phone'] = 'nullable|unique:users,phone';
        } else {
            $rules['email'] = 'required|email|unique:users,email,' . $id;
            $rules['phone'] = 'nullable|unique:users,phone,' . $id;
        }

        return $rules;
    }
}

app/Http/Controllers/Member/BranchController.php
<?php

namespace App\Http\Controllers\Member;

use App\DataTables\BranchDataTable;
use App\Models\Branch;
use App\Models\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(BranchDataTable $dataTable)
    {
        return $dataTable->render('member.branches.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['countries'] = Country::all()->pluck('countryName', 'id');

        return view('member.branches.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, $this->validationRules());

        $inputs = $request->all();
        $inputs['name'] = human_words($inputs['display_name']);
        Branch::create($inputs);


        $status = ['type' => 'success', 'message' => 'Successfully Added.'];

        return back()->with('status', $status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['model'] = Branch::findOrFail($id);
        $data['countries'] = Country::all()->pluck('countryName', 'id');

        return view('member.branches.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Branch::findOrFail($id);
        $this->validate($request, $this->validationRules());

        $inputs = $request->all();
        $inputs['name'] = human_words($inputs['display_name']);
        $company->update($inputs);

        $status = ['type' => 'success', 'message' => 'Successfully Updated'];

        return back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function validationRules(){

        $rules = [
            'display_name' => 'required',
            'phone' => 'required',
        ];

        return $rules;
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
     public function index(){
        return view('member.dashboard.index');
    }
}

resources/views/member/items/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 4:25 PM
 */

?>

@push('styles')

    <link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/select2/dist/css/select2.min.css')}}">
@endpush


    <div class="col-md-6">
        <div class="form-group">
            <label for="item_name">Item Name <span class="text-red"> * </span> </label>
            {!! Form::text('item_name',null,['id'=>'item_name','class'=>'form-control','placeholder'=>'Enter Item Name', 'required']); !!}
        </div>
        <div class="form-group">
            <label for="item_name">SkuCode <span class="text-red"> * </span> </label>
            {!! Form::text('skuCode',null,['id'=>'sku_code','class'=>'form-control','placeholder'=>'Enter Sku Code']); !!}
        </div>
        <div class="form-group">
            <label for="item_name"> Product Code <span class="text-red"> * </span> </label>
            {!! Form::text('productCode',null,['id'=>'product_code','class'=>'form-control','placeholder'=>'Enter  Product Code', 'required']); !!}
        </div>
        <div class="form-group">
            <label for="status">Product Category <span class="text-red"> * </span>  </label>
            {!! Form::select('category_id',$categories, null,['id'=>'category_id','class'=>'form-control select2','placeholder'=>'Please select status', 'required']); !!}
        </div>
        <div class="form-group">
            <label for="product_image">Product Image  </label>
            {!! Form::file('product_image', null,['id'=>'product_image', 'accept'=>'image/*' , 'class'=>'form-control','placeholder'=>'Enter Title' , ]); !!}
        </div>
        <div class="form-group">
            <label for="status">Unit <span class="text-red"> * </span>  </label>
            {!! Form::select('unit', $units, null,['id'=>'unit','class'=>'form-control','placeholder'=>'Please select Unit', 'required']); !!}
        </div>
        <div class="form-group">
            <label for="warranty"> Price  <span class="text-red"> * </span> </label>
            {!! Form::number('price',null,['id'=>'price','class'=>'form-control','placeholder'=>'Enter Price', 'required']); !!}
        </div>
        <div class="form-group">
            <label for="status">Status <span class="text-red"> * </span>  </label>
            {!! Form::select('status',['active'=>'Active', 'inactive'=>'Inactive'], null,['id'=>'status','class'=>'form-control', 'required']); !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="description">Description </label>
            {!! Form::textarea('description',null,['id'=>'description','class'=>'form-control','placeholder'=>'Enter description']); !!}
        </div>
        <div class="form-group">
            <label for="warranty"> Item Warranty </label>
            {!! Form::number('warranty',null,['id'=>'warranty','class'=>'form-control','placeholder'=>'Enter warranty']); !!}
        </div>
        <div class="form-group">
            <label for="warranty"> Item Guarantee </label>
            {!! Form::number('guarantee',null,['id'=>'guarantee','class'=>'form-control','placeholder'=>'Enter Guarantee']); !!}
        </div>
    </div>



@push('scripts')

    <!-- Select2 -->
    <script src="{{ asset('public/adminLTE/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <!-- CK Editor -->
    <script src="{{ asset('public/adminLTE/bower_components/ckeditor/ckeditor.js') }}"></script>


    <script type="text/javascript">
        $(function () {

            $('.select2').select2()
        });

    </script>


@endpush

resources/views/member/items/barcode_print_form.blade.php
<?php
/**
 * Print Barcoded by PhpStorm.
 * User: Mobarok Hossen
 * Date: 8/29/2019
 * Time: 1:15 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('member.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Products',
        'href' => route('member.items.index'),
    ],
    [
        'name' => 'Print Barcode',
    ],
];

$data['data'] = [
    'name' => 'Products',
    'title'=>'Print Barcode Product',
    'heading' => 'Print Barcode Product',
];

?>
@extends('layouts.back-end.master', $data)
@push('styles')
    <link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/select2/dist/css/select2.min.css')}}">
@endpush
@section('contents')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">

        @include('common._alert')

        @include('common._error')
        <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Print Barcode Product</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                <div class="box-body">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="item_name">Product Name <span class="text-red"> * </span> </label>
                            {!! Form::select('item_id', $products, null,['id'=>'item_id', 'class'=>'form-control select2','required', 'placeholder'=>'Select Item Name']); !!}
                        </div>
                        <div class="form-group">
                            <label for="warranty"> Print Qty  <span class="text-red"> * </span> </label>
                            {!! Form::text('print_qty',null,['id'=>'print_qty','class'=>'form-control input-number','placeholder'=>'Enter Print Quantity', 'required']); !!}
                        </div>
                    </div>

                    <div class="box-footer">
                        <div class="col-md-12">
                            <a href="#" class=" btn btn-sm btn-primary hidden" id="btn-print"> <i class="fa fa-print"></i> Submit </a>
                            <a href="#" class=" btn btn-sm btn-primary" id="print-barcode"> <i class="fa fa-print"></i> Submit </a>
                        </div>
                    </div>

                </div>
            <!-- /.box -->
            </div>
        </div>
    </div>
@endsection


@push('scripts')
   <script src="{{ asset('public/adminLTE/bower_components/select2/dist/js/select2.full.min.js') }}"></script>

    <!-- Date range picker -->
    <script type="text/javascript">

        // var date = new Date();
        $(function () {
            $('.select2').select2();

            $('#print-barcode').click( function (e) {
                var item_id = $("#item_id").val();
                var print_qty = $("#print_qty").val();
                if( item_id == '' || print_qty == '') {
                    if(item_id == "")
                    {
                        bootbox.alert("Please select product Name");
                    }else{
                        bootbox.alert("Please select print Qty");
                    }
                    return false;
                }
               var link = "{{ route('member.items.print_barcode') }}"+"?item_id="+item_id+"&print_qty="+print_qty;
               // alert(link);
                $("#btn-print").attr("href", link);
                $("#btn-print").trigger('click');
               //  $("#print-barcode").attr("href", link);
               //  $("#print-barcode").trigger('click');
            });
        });
        </script>
@endpush

resources/views/member/items/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 12:52 PM
 */
$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Items/Products',
        'href' => route('member.items.index'),
    ],
    [
        'name' => 'Edit',
    ],
];

$data['data'] = [
    'name' => 'Items/Products',
    'title'=>'Edit Item/Product',
    'heading' => 'Edit Item/Product',
];

?>
@extends('layouts.back-end.master', $data)

@section('contents')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">

            @include('common._alert')

            @include('common._error')
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Update </h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                {!! Form::model($modal, ['route' => ['member.items.update', $modal],  'method' => 'put', 'role'=>'form', 'files'=>true]) !!}

                <div class="box-body">

                    @include('member.items._form')

                    <div class="box-footer">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->

            {!! Form::close() !!}
            <!-- /.box -->
            </div>
        </div>
    </div>
@endsection


@push('scripts')

    <!-- CK Editor -->
    <script src="{{ asset('public/adminLTE/bower_components/ckeditor/ckeditor.js') }}"></script>

    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('description');
        })
    </script>
@endpush

resources/views/member/items/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Items/Products',
        'href' => route('member.items.index'),
    ],
    [
        'name' => 'Index',
    ],
];

$data['data'] = [
    'name' => 'Items/Products',
    'title'=>'List Of Items/Products', 
    'heading' => 'List Of Items/Products',
];

?>

@extends('layouts.back-end.master', $data)

@section('contents')


    <div class="row">
        <div class="col-xs-12">

            @include('common._alert')

            <div class="box">
                <div class="portlet light">

                    <div class="box-header">
                        <a href="{{ route('member.items.create') }}" class="btn btn-info"> <i class="fa fa-plus"> Add Item/Product </i></a>
                    </div>
                    <!-- END SAMPLE FORM PORTLET-->
                </div>
                <div class="box-body">
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <!-- BEGIN SAMPLE FORM PORTLET-->

                        <div class="table-responsive">
                            {!! $dataTable->table() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('public/vendor/datatables/buttons.server-side.js') }}"></script>
    {!! $dataTable->scripts() !!}
@endpush

resources/views/member/items/show_product_barcode.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 8/29/2019
 * Time: 2:57 PM
 */



$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('member.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Barcode',
        'href' => route('member.items.print_barcode_form'),
    ],
    [
        'name' => 'Product Barcode Print',
    ],
];

$data['data'] = [
    'name' => 'Product Barcode Print',
    'title'=> 'Product Barcode Print',
    'heading' => 'Product Barcode Print',
];

?>
@extends('layouts.back-end.master', $data)

@push('styles')
    <style type="text/css">

        .per-barcode{
            margin-right: 25px;
            width: 120px;
            height: 80px;
            text-align: center;
            float: left;
            margin-bottom: 20px;
        }

        .per-barcode div{
            text-align: center !important;
            margin-left: 7px;
        }
        .per-barcode h4{
            margin: 5px 0;
            font-size: 15px;
        }
        .per-barcode p{
            text-align: center;
            margin: 5px 0;
            font-size: 12px;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/select2/dist/css/select2.min.css')}}">
@endpush

@section('contents')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Product Barcode</h3>
                    <a href="{{ route(Route::current()->getName()) == $full_url ? route(Route::current()->getName())."?" : $full_url."item_id=".$item->id."&print_qty=".$print_qty.'&' }}type=print" class="pull-right btn btn-sm btn-primary" id="btn-print"> <i class="fa fa-print"></i> Print </a>
                </div>

                <div class="box-body">

                    <div class="col-lg-12">
                        @for($i=1; $i<=$print_qty; $i++)
                            <div class="per-barcode">
                                {{--                <p>{{ $company_name }}</p>--}}
                                <p>{{ $item->item_name }}</p>
                                <p>@php print_r($barcode) @endphp</p>
                                <p>{{ $item->productCode }}</p>
                                <h4>{{ "TK ".$item->price }}</h4>
                            </div>
                        @endfor
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection